request_type: "passport" #this value should be either citizenship or passport
# Only uses the following if using the passport
has_under_age_children: "No" #Yes or No
total_children: "0" # Total number of children
possess_expired_passport: "No" # Yes or No
full_address: "Your full adress should be placed here" # Full residential address
marital_status: ""